import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

String tr(String key, {String? defaultText}) {
  return LanguageService.instance.translate(key, defaultText: defaultText);
}

extension StringTranslationExtension on String {
  String get tr => LanguageService.instance.translate(this);
}

class LanguageService {
  LanguageService._();
  static final LanguageService instance = LanguageService._();

  static const String _prefKey = 'app_language_code';

  static final ValueNotifier<String> currentLocaleNotifier = ValueNotifier<String>('en');
  static String tr(String key, {String? defaultText}) => instance.translate(key, defaultText: defaultText);

  String get currentCode => currentLocaleNotifier.value;

  String get currentLanguageName {
    switch (currentCode) {
      case 'ta':
        return 'தமிழ்';
      case 'hi':
        return 'हिन्दी';
      default:
        return 'English';
    }
  }

  Future<void> initialize() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final saved = prefs.getString(_prefKey);
      if (saved != null && saved.isNotEmpty) {
        currentLocaleNotifier.value = saved;
      }
    } catch (e) {
      debugPrint('LanguageService init error: $e');
    }
  }

  Future<void> setLanguage(String code) async {
    currentLocaleNotifier.value = code;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_prefKey, code);
    } catch (e) {
      debugPrint('LanguageService save error: $e');
    }
  }

  static final Map<String, String> _lookupCache = <String, String>{};
  static Map<String, String>? _normalizedIndex;

  static Map<String, String> _getNormalizedIndex() {
    if (_normalizedIndex != null) return _normalizedIndex!;
    final map = <String, String>{};
    final enDict = _translations['en']!;
    for (final entry in enDict.entries) {
      final keyNorm = entry.key.trim().toLowerCase();
      final valNorm = entry.value.trim().toLowerCase();
      map.putIfAbsent(keyNorm, () => entry.key);
      map.putIfAbsent(valNorm, () => entry.key);
    }
    _normalizedIndex = map;
    return map;
  }

  /// Looks up translation by key or by exact English phrase in O(1) time
  String translate(String key, {String? defaultText}) {
    final code = currentCode;
    final cacheKey = '$code:$key';
    final cached = _lookupCache[cacheKey];
    if (cached != null) return cached;

    final dict = _translations[code] ?? _translations['en']!;

    // 1. Direct key match in current language
    if (dict.containsKey(key)) {
      final res = dict[key]!;
      _lookupCache[cacheKey] = res;
      return res;
    }

    // 2. Pre-indexed lookup by normalized English phrase or key
    final normIndex = _getNormalizedIndex();
    final normalized = key.trim().toLowerCase();
    final dictKey = normIndex[normalized];
    if (dictKey != null) {
      final res = dict[dictKey] ?? _translations['en']![dictKey];
      if (res != null) {
        _lookupCache[cacheKey] = res;
        return res;
      }
    }

    // 3. Fallback to English dictionary direct key
    final enDict = _translations['en']!;
    if (enDict.containsKey(key)) {
      final res = enDict[key]!;
      _lookupCache[cacheKey] = res;
      return res;
    }

    final fallback = defaultText ?? key;
    _lookupCache[cacheKey] = fallback;
    return fallback;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      // General & App Branding
      'app_title': 'KisanAI',
      'app_subtitle': 'Direct Farm AI',
      'welcome': 'Welcome!',
      'welcome_subtitle': 'Choose how you want to use KisanAI',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'manage_farm_intro': 'Manage your farm, products and orders all in one place.',
      'wallet_balance': 'Wallet Balance',
      'view_transactions': 'View Transactions ›',
      'view_analytics': 'View Analytics ↗',
      'today_overview': "Today's Overview",
      'recent_orders': 'Recent Orders',
      'view_all': 'View All',
      'switch_language': 'Switch Language',
      'choose_language': 'Choose Your Language',
      'select_preferred_language': 'Select your preferred language',
      'continue_button': 'Continue',
      'continue_to_login': 'Continue to Login',
      'call': 'Call',
      'track': 'Track',
      'notes': 'Notes',

      // Roles
      'farmer': 'Farmer',
      'buyer': 'Buyer',
      'delivery_partner': 'Delivery Partner',

      // Navigation Bar (Farmer & Buyer)
      'Home': 'Home',
      'Products': 'Products',
      'Produce': 'Produce',
      'Orders': 'Orders',
      'Auction': 'Auction',
      'Messages': 'Messages',
      'Market': 'Market',
      'Wishlist': 'Wishlist',
      'Profile': 'Profile',
      'nav_home': 'Home',
      'nav_products': 'Products',
      'nav_produce': 'Produce',
      'nav_orders': 'Orders',
      'nav_auction': 'Auction',
      'nav_messages': 'Messages',
      'nav_market': 'Market',
      'nav_wishlist': 'Wishlist',
      'nav_profile': 'Profile',

      // Quick Actions
      'Quick Actions': 'Quick Actions',
      'quick_actions': 'Quick Actions',
      'voice_assistant': 'Voice Assistant',
      'quality_scanner': 'AI Quality Scan',
      'kisan_pool': 'KisanPool Logistics',
      'offline_sync': 'Offline Sync',
      'track_vehicle': 'Track Transport',
      'add_product': 'Add Produce',
      'manage_products': 'Manage Products',
      'analytics': 'Analytics',
      'payouts': 'Payouts',
      'talk_with_buyers': 'Talk with your buyers',

      // Overview Stats
      'new_orders': 'New Orders',
      'New Orders': 'New Orders',
      'in_progress': 'In Progress',
      'In Progress': 'In Progress',
      'completed': 'Completed',
      'Completed': 'Completed',
      'today_earnings': "Today's Earnings",
      "Today's Earnings": "Today's Earnings",
      'no_new_orders': 'No new orders',
      'no_orders': 'No orders',
      'from_completed': 'From completed orders',

      // Buyer Home
      'fresh_from_farms': 'Fresh from Farms',
      'Fresh from Farms': 'Fresh from Farms',
      'search_placeholder': 'Search fresh vegetables, fruits...',
      'Shop by Category': 'Shop by Category',
      'shop_by_category': 'Shop by Category',
      'Fresh Picks for You': 'Fresh Picks for You',
      'fresh_picks': 'Fresh Picks for You',
      'Direct Farm Delivery': 'Direct Farm Delivery',
      'direct_farm_delivery': 'Direct Farm Delivery',
      'direct_delivery_desc': 'Fast, hygienic cold-chain transport straight from local farms to your doorstep.',
      'add_to_cart': 'Add to Cart',
      'Add to Cart': 'Add to Cart',
      'buy_now': 'Buy Now',
      'Buy Now': 'Buy Now',
      'All': 'All',
      'all': 'All',
      'Vegetables': 'Vegetables',
      'vegetables': 'Vegetables',
      'Fruits': 'Fruits',
      'fruits': 'Fruits',
      'Grains': 'Grains',
      'grains': 'Grains',
      'Spices': 'Spices',
      'spices': 'Spices',
      'Oil Seeds': 'Oil Seeds',
      'oil_seeds': 'Oil Seeds',

      // Orders Screen
      'my_orders': 'My Orders',
      'My Orders': 'My Orders',
      'track_manage_orders': 'Track and manage your orders',
      'all_orders': 'All Orders',
      'All Orders': 'All Orders',
      'Ongoing': 'Ongoing',
      'ongoing': 'Ongoing',
      'Delivered': 'Delivered',
      'delivered': 'Delivered',
      'Cancelled': 'Cancelled',
      'cancelled': 'Cancelled',
      'Placed': 'Placed',
      'placed': 'Placed',
      'Confirmed': 'Confirmed',
      'confirmed': 'Confirmed',
      'Preparing': 'Preparing',
      'preparing': 'Preparing',
      'Picked Up': 'Picked Up',
      'picked_up': 'Picked Up',
      'Out for Delivery': 'Out for Delivery',
      'out_for_delivery': 'Out for Delivery',
      'total_amount': 'Total Amount',
      'Total Amount': 'Total Amount',
      'payment_status': 'Payment Status',
      'payment_paid': 'Payment Paid',
      'payment_pending': 'Payment Pending',
      'view_details': 'View Details',
      'View Details': 'View Details',

      // Transport & Vehicle Assignment
      'assign_transport_title': 'Assign Delivery Partner (Optional)',
      'assign_transport_subtitle': 'Select verified reefer or cargo logistics for this order',
      'assign_transport_optional': 'Assign Transport (Optional)',
      'change_vehicle_optional': 'Change Vehicle (Optional)',
      'confirm_assign_vehicle': 'Confirm Vehicle Assignment',
      'transport': 'Transport',
      'driver': 'Driver',
      'vehicle': 'Vehicle',
      'driver_rating': 'Driver Rating',
      'est_delivery_time': 'Estimated Delivery Time',
      'zero_damage_guarantee': 'Zero-Damage & Correct Location Pin Guarantee',
      'mutual_assign_notice': 'Either Farmer or Buyer can select or change this vehicle upon mutual communication.',
      'call_driver': 'Call Driver',
      'call_farmer': 'Call Farmer',
      'call_buyer': 'Call Buyer',
      'todays_weather': "Today's Weather",
      'farmer_details': 'Farmer & Farm Details',
      'direct_from_origin': 'Direct farm produce origin verified',
      'quality_checked': 'Grade-A Quality Verified',
      'otp': 'OTP',
      'pickup_otp': 'Pickup OTP',
      'delivery_otp': 'Delivery OTP',
      'eat_fresh': 'Eat Fresh,',
      'Eat Fresh,': 'Eat Fresh,',
      'stay_healthy': 'Stay Healthy',
      'Stay Healthy': 'Stay Healthy',
      'hero_subtitle': 'Handpicked produce\ndirectly from farmers 🌱',
      'shop_now': 'Shop Now',
      'Shop Now': 'Shop Now',
      'free_delivery_banner': 'Free Delivery above ₹499',
      'free_delivery_desc': 'Support farmers. Eat fresh.',
      'see_all': 'See All',
      'See All': 'See All',
      'menu': 'Menu',
      'auctions': 'Auctions',
      'bid_fresh_products': 'Bid on fresh products',
      'chat_with_farmers': 'Chat with Farmers',
      'favorites': 'Favorites',
      'todays_deals': "Today's Deals",
      'change_location': 'Change Location',
      'help_support': 'Help & Support',
      'settings': 'Settings',
      'logout': 'Logout',
      'logout_subtitle': 'Sign out of your account',
      'logout_dialog_title': 'Logout?',
      'logout_dialog_msg': 'Are you sure you want to logout from KisanAI?',
      'cancel': 'Cancel',
      'retry': 'Retry',
      'search_orders_hint': 'Search orders by ID or buyer...',
      'no_orders_found': 'No Orders Found',
      'new_buyer_orders_hint': 'New buyer orders will appear here.',
      'load_sample_orders': 'Load Sample Orders',
      'load_sample_success': 'Sample orders loaded successfully! 🌱',
      'available_label': 'Available: ',
      'verified_driver': 'Verified Driver',
      'vehicle_specs': 'Vehicle Specs',
      'express_delivery': 'Express Delivery',
      'no_products_category': 'No products in this category',
      'no_fresh_products': 'No fresh products available',
      'farmers_not_listed': "Farmers haven't listed any available products yet.",
      'try_another_category': 'Try selecting another category.',
      'view_all_products': 'View All Products',
      'unable_to_load': 'Unable to load products',
      'unable_to_load_orders': 'Unable to load orders',

      // Dynamic Crops
      'Tomato': 'Tomato',
      'Potato': 'Potato',
      'Onion': 'Onion',
      'Rice': 'Rice',
      'Paddy': 'Paddy',
      'Wheat': 'Wheat',
      'Carrot': 'Carrot',
      'Banana': 'Banana',
      'Mango': 'Mango',
      'Chilli': 'Chilli',
      'Green Chilli': 'Green Chilli',
      'Brinjal': 'Brinjal',
      'Eggplant': 'Eggplant',
      'Cabbage': 'Cabbage',
      'Cauliflower': 'Cauliflower',
      'Garlic': 'Garlic',
      'Ginger': 'Ginger',
      'Spinach': 'Spinach',
      'Corn': 'Corn',
      'Maize': 'Maize',
      'Coconut': 'Coconut',
      'Apple': 'Apple',
      'Turmeric': 'Turmeric',
      'Cotton': 'Cotton',
      'Sugarcane': 'Sugarcane',
      'Lady\'s Finger': 'Lady\'s Finger',
      'Okra': 'Okra',
      'Capsicum': 'Capsicum',
      'Cucumber': 'Cucumber',
      'Beetroot': 'Beetroot',
      'Coriander': 'Coriander',
      'Mint': 'Mint',
      'Drumstick': 'Drumstick',
      'Groundnut': 'Groundnut',
      'Peanut': 'Peanut',
      'Cardamom': 'Cardamom',
      'Pepper': 'Pepper',
      'Black Pepper': 'Black Pepper',

      // Order Statuses
      'Pending': 'Pending',
      'pending': 'Pending',
      'Processing': 'Processing',
      'processing': 'Processing',
      'In Transit': 'In Transit',
      'in_transit': 'In Transit',
      'Shipped': 'Shipped',
      'shipped': 'Shipped',
      'Refunded': 'Refunded',
      'refunded': 'Refunded',
      'New': 'New',

      // Weather Conditions & Details
      'Sunny': 'Sunny',
      'sunny': 'Sunny',
      'Rainy': 'Rainy',
      'rainy': 'Rainy',
      'Clear': 'Clear',
      'clear': 'Clear',
      'Cloudy': 'Cloudy',
      'cloudy': 'Cloudy',
      'Partly Cloudy': 'Partly Cloudy',
      'partly_cloudy': 'Partly Cloudy',
      'Overcast': 'Overcast',
      'overcast': 'Overcast',
      'Mist': 'Mist',
      'mist': 'Mist',
      'Fog': 'Fog',
      'fog': 'Fog',
      'Thunderstorm': 'Thunderstorm',
      'thunderstorm': 'Thunderstorm',
      'Drizzle': 'Drizzle',
      'drizzle': 'Drizzle',
      'Weather Forecast': 'Weather Forecast',
      'weather_forecast': 'Weather Forecast',
      'Feels Like': 'Feels Like',
      'feels_like': 'Feels Like',
      'Humidity': 'Humidity',
      'humidity': 'Humidity',
      'Wind': 'Wind',
      'wind': 'Wind',
      'Precipitation': 'Precipitation',
      'precipitation': 'Precipitation',

      // Filters, Sorting & Cart
      'filter': 'Filter',
      'Filter': 'Filter',
      'filter_orders': 'Filter Orders',
      'filter_and_sort': 'Filter & Sort',
      'Filter & Sort': 'Filter & Sort',
      'sort_by': 'Sort By',
      'Sort By': 'Sort By',
      'price_low_high': 'Price: Low to High',
      'Price: Low to High': 'Price: Low to High',
      'price_high_low': 'Price: High to Low',
      'Price: High to Low': 'Price: High to Low',
      'lowest_price': 'Lowest Price',
      'Lowest Price': 'Lowest Price',
      'highest_price': 'Highest Price',
      'Highest Price': 'Highest Price',
      'quantity_high_low': 'Quantity: High to Low',
      'Quantity: High to Low': 'Quantity: High to Low',
      'newest': 'Newest',
      'Newest': 'Newest',
      'rating': 'Rating',
      'Rating': 'Rating',
      'all_statuses': 'All Statuses',
      'All Statuses': 'All Statuses',
      'transport_assigned': 'Transport Assigned',
      'Transport Assigned': 'Transport Assigned',
      'transport_unassigned': 'Transport Not Assigned',
      'Transport Not Assigned': 'Transport Not Assigned',
      'reset': 'Reset',
      'Reset': 'Reset',
      'apply': 'Apply',
      'Apply': 'Apply',
      'apply_filters': 'Apply Filters',
      'Apply Filters': 'Apply Filters',
      'items': 'Items',
      'Items': 'Items',
      'total': 'Total',
      'Total': 'Total',
      'checkout': 'Proceed to Checkout',
      'Checkout': 'Proceed to Checkout',
      'empty_cart': 'Your cart is empty',
      'empty_cart_desc': 'Explore farm products and add them to your cart.',

      // Farmer Hub (SellScreen)
      'farmer_hub': 'My Farmer Hub',
      'My Farmer Hub': 'My Farmer Hub',
      'my_products': 'My Products',
      'My Products': 'My Products',
      'refresh_listings': 'Refresh Listings',
      'Refresh Listings': 'Refresh Listings',
      'farmer_home': 'Farmer Home',
      'Farmer Home': 'Farmer Home',
      'list_your_produce': 'List Your Produce',
      'List Your Produce': 'List Your Produce',
      'reach_buyers_ai': 'Reach buyers directly using AI pricing assistant.',
      'add_new': 'Add New',
      'Add New': 'Add New',
      'my_listings': 'My Listings',
      'My Listings': 'My Listings',
      'active': 'Active',
      'Active': 'Active',
      'sold': 'Sold',
      'Sold': 'Sold',
      'sold_out': 'Sold Out',
      'Sold Out': 'Sold Out',
      'no_products_yet': 'No products listed yet',
      'tap_add_new_intro': "Tap 'Add New' above to list your produce.",
      'load_starter_products': 'Load Starter Products',
      'products_found': 'products found',
      'no': 'No',

      // Auction Screen
      'manage_product_auctions': 'Manage your product auctions',
      'my_auctions': 'My Auctions',
      'My Auctions': 'My Auctions',
      'upcoming': 'Upcoming',
      'Upcoming': 'Upcoming',
      'search_auctions_hint': 'Search auctions...',
      'start_price': 'Start Price',
      'Start Price': 'Start Price',
      'current_highest_bid': 'Current Highest Bid',
      'Current Highest Bid': 'Current Highest Bid',
      'bids': 'Bids',
      'Bids': 'Bids',
      'live': 'LIVE',
      'LIVE': 'LIVE',
      'ends_in': 'Ends in',
      'Ends in': 'Ends in',
      'starts_in': 'Starts in',
      'Starts in': 'Starts in',
      'final_price': 'Final Price',
      'Final Price': 'Final Price',
      'winner': 'Winner',
      'Winner': 'Winner',
      'create_new_auction': 'Create New Auction',
      'Create New Auction': 'Create New Auction',
      'filter_auctions': 'Filter Auctions',
      'no_auctions_found': 'No auctions found',
      'place_bid': 'Place Bid',
      'enter_bid_amount': 'Enter bid amount',
      'minimum_bid': 'Minimum Bid',
      'auction_details': 'Auction Details',

      // Weather & Insights
      'view': 'View',
      'View': 'View',
      '7_day_forecast': '7-Day Forecast',
      'farming_insights': 'Farming Insights',
      'best_irrigation_time': 'Best irrigation time: 6 AM - 8 AM',
      'no_heavy_rain': 'No heavy rainfall expected today.',
      'suitable_harvest': 'Suitable day for harvesting.',
      'Today': 'Today',
      'Tomorrow': 'Tomorrow',
      'Sunday': 'Sunday',
      'Monday': 'Monday',
      'Tuesday': 'Tuesday',
      'Wednesday': 'Wednesday',
      'Thursday': 'Thursday',
      'Friday': 'Friday',
      'Saturday': 'Saturday',
      'uv_index': 'UV Index',
      'High': 'High',
      'high': 'High',

      // Delivery Partner
      'kisanai_delivery': 'KisanAI Delivery',
      'connecting_farms_families': 'Connecting Farms to Families',
      'deliver_fresh_produce_today': "Let's deliver fresh produce today!",
      'todays_deliveries': "Today's Deliveries",
      'total_completed': 'Total Completed',
      'offline': 'OFFLINE',
      'online': 'ONLINE',
      'accepting_orders': 'Accepting Orders',
      'map': 'Map',
      'profile': 'Profile',
      'no_new_orders_pickup': 'No new delivery orders right now',
      'ready_for_pickup_realtime': 'Orders ready for pickup will appear here in real time.',
      'accept_delivery': 'Accept Delivery',
      'continue_job': 'Continue Job',
      'start_navigation': 'Start Navigation',
      'start_pickup': 'Start Pickup',
      'pickup_location': 'Go to Pickup Location',
      'live_delivery_map': 'Live Delivery Map',
      'delivery_fee': 'Delivery Fee',
      'pickup_address': 'Pickup Address',
      'drop_address': 'Drop Address',
      'no_active_orders': 'No active deliveries',
      'no_completed_orders': 'No completed deliveries yet',
      'navigate_to_farm': 'Navigate to Farm',
      'fastest_route': 'Fastest Route',
      'moderate_traffic': 'Moderate Traffic',
      'clear_traffic': 'Clear Traffic',
      'heavy_traffic': 'Heavy Traffic',
      'alternate_route': 'Alternate Route',

      // Entrance & Taglines
      'smart_agriculture_tagline': 'Smart Agriculture & Direct Market 🌾',
      'Smart Agriculture & Direct Market 🌾': 'Smart Agriculture & Direct Market 🌾',
      'get_started': 'Get Started',
      'Get Started': 'Get Started',
      'already_have_account': 'Already have an account? ',
      'Already have an account? ': 'Already have an account? ',
      'farmer_role_desc': 'Sell your produce,\nconnect with buyers.',
      'buyer_role_desc': 'Buy fresh produce\ndirect from farmers.',
      'delivery_role_desc': 'Deliver fresh farm produce & earn on every trip.',
      'Deliver fresh farm produce & earn on every trip.': 'Deliver fresh farm produce & earn on every trip.',
      'trusted': 'Trusted',
      'Trusted': 'Trusted',
      'safe_and_secure': 'Safe & secure',
      'Safe & secure': 'Safe & secure',
      'fresh': 'Fresh',
      'Fresh': 'Fresh',
      'farm_quality': 'Farm quality',
      'Farm quality': 'Farm quality',
      'fast': 'Fast',
      'Fast': 'Fast',
      'quick_delivery': 'Quick delivery',
      'Quick delivery': 'Quick delivery',
      'together_grow_better': 'Together, let’s grow a better tomorrow 💚',
      'Together, let’s grow a better tomorrow 💚': 'Together, let’s grow a better tomorrow 💚',
      'Together, let\'s grow a better tomorrow 💚': 'Together, let’s grow a better tomorrow 💚',
      'support_farmers_eat_fresh': 'Support farmers. Eat fresh. Live healthy.',
      'Support farmers. Eat fresh. Live healthy.': 'Support farmers. Eat fresh. Live healthy.',

      // Produce Varieties
      'Sweet Golden Corn': 'Sweet Golden Corn',
      'Fresh Farm Bananas (Nendran)': 'Fresh Farm Bananas (Nendran)',
      'Sona Masoori Paddy (Grade A)': 'Sona Masoori Paddy (Grade A)',
      'Organic Tomato (Fresh Harvest)': 'Organic Tomato (Fresh Harvest)',
      'Banganapalli Mango (Grade A)': 'Banganapalli Mango (Grade A)',

      'Change Vehicle': 'Change Vehicle',
    },
    'ta': {
      // General & App Branding
      'app_title': 'கிசான் AI',
      'app_subtitle': 'நேரடி பண்ணை AI',
      'welcome': 'வரவேற்கிறோம்!',
      'welcome_subtitle': 'கிசான் AI-ஐ எவ்வாறு பயன்படுத்த விரும்புகிறீர்கள் என்பதை தேர்வு செய்யவும்',
      'good_morning': 'காலை வணக்கம்',
      'good_afternoon': 'மதிய வணக்கம்',
      'good_evening': 'மாலை வணக்கம்',
      'manage_farm_intro': 'உங்கள் பண்ணை, விளைபொருட்கள் மற்றும் ஆர்டர்களை ஒரே இடத்தில் நிர்வகியுங்கள்.',
      'wallet_balance': 'பணப்பை இருப்பு',
      'view_transactions': 'பரிவர்த்தனைகளை பார்க்க ›',
      'view_analytics': 'புள்ளிவிவரங்களை பார்க்க ↗',
      'today_overview': 'இன்றைய கண்ணோட்டம்',
      'recent_orders': 'சமீபத்திய ஆர்டர்கள்',
      'view_all': 'அனைத்தையும் பார்க்க',
      'switch_language': 'மொழியை மாற்றவும்',
      'choose_language': 'மொழியை தேர்வு செய்யவும்',
      'select_preferred_language': 'உங்கள் விருப்ப மொழியை தேர்ந்தெடுக்கவும்',
      'continue_button': 'தொடரவும்',
      'continue_to_login': 'உள்நுழைய தொடரவும்',
      'call': 'அழைக்க',
      'track': 'கண்காணிக்க',
      'notes': 'குறிப்புகள்',

      // Roles
      'farmer': 'விவசாயி',
      'buyer': 'வாங்குபவர்',
      'delivery_partner': 'விநியோக பங்குதாரர்',

      // Navigation Bar (Farmer & Buyer)
      'Home': 'முகப்பு',
      'Products': 'விளைபொருட்கள்',
      'Produce': 'விளைபொருட்கள்',
      'Orders': 'ஆர்டர்கள்',
      'Auction': 'ஏலம்',
      'Messages': 'செய்திகள்',
      'Market': 'சந்தை',
      'Wishlist': 'விருப்பப்பட்டியல்',
      'Profile': 'சுயவிவரம்',
      'nav_home': 'முகப்பு',
      'nav_products': 'விளைபொருட்கள்',
      'nav_produce': 'விளைபொருட்கள்',
      'nav_orders': 'ஆர்டர்கள்',
      'nav_auction': 'ஏலம்',
      'nav_messages': 'செய்திகள்',
      'nav_market': 'சந்தை',
      'nav_wishlist': 'விருப்பப்பட்டியல்',
      'nav_profile': 'சுயவிவரம்',

      // Quick Actions
      'Quick Actions': 'விரைவு செயல்கள்',
      'quick_actions': 'விரைவு செயல்கள்',
      'voice_assistant': 'குரல் உதவியாளர்',
      'quality_scanner': 'AI தர ஸ்கேனர்',
      'kisan_pool': 'கிசான்பூல் வாகனம்',
      'offline_sync': 'ஆஃப்லைன் ஒத்திசைவு',
      'track_vehicle': 'வாகனம் கண்காணிக்க',
      'add_product': 'பயிர் சேர்க்க',
      'manage_products': 'பயிர்களை நிர்வகிக்க',
      'analytics': 'பகுப்பாய்வு',
      'payouts': 'பணம் வழங்கல்',
      'talk_with_buyers': 'வாங்குபவர்களுடன் அரட்டையடிக்கவும்',

      // Overview Stats
      'new_orders': 'புதிய ஆர்டர்கள்',
      'New Orders': 'புதிய ஆர்டர்கள்',
      'in_progress': 'செயலில் உள்ளவை',
      'In Progress': 'செயலில் உள்ளவை',
      'completed': 'முடிந்தவை',
      'Completed': 'முடிந்தவை',
      'today_earnings': 'இன்றைய வருமானம்',
      "Today's Earnings": 'இன்றைய வருமானம்',
      'no_new_orders': 'புதிய ஆர்டர்கள் இல்லை',
      'no_orders': 'ஆர்டர்கள் இல்லை',
      'from_completed': 'முடிந்த ஆர்டர்களில் இருந்து',

      // Buyer Home
      'fresh_from_farms': 'பண்ணை பசுமை',
      'Fresh from Farms': 'பண்ணை பசுமை',
      'search_placeholder': 'புதிய காய்கறிகள், பழங்களை தேடுங்கள்...',
      'Shop by Category': 'வகைகள் மூலம் வாங்குங்கள்',
      'shop_by_category': 'வகைகள் மூலம் வாங்குங்கள்',
      'Fresh Picks for You': 'உங்களுக்கான புதிய விளைபொருட்கள்',
      'fresh_picks': 'உங்களுக்கான புதிய விளைபொருட்கள்',
      'Direct Farm Delivery': 'நேரடி பண்ணை விநியோகம்',
      'direct_farm_delivery': 'நேரடி பண்ணை விநியோகம்',
      'direct_delivery_desc': 'உள்ளூர் பண்ணைகளிலிருந்து உங்கள் வாசலுக்கே நேரடி குளிர்பதன போக்குவரத்து.',
      'add_to_cart': 'கார்ட்டில் சேர்க்க',
      'Add to Cart': 'கார்ட்டில் சேர்க்க',
      'buy_now': 'இப்போதே வாங்க',
      'Buy Now': 'இப்போதே வாங்க',
      'All': 'அனைத்தும்',
      'all': 'அனைத்தும்',
      'Vegetables': 'காய்கறிகள்',
      'vegetables': 'காய்கறிகள்',
      'Fruits': 'பழங்கள்',
      'fruits': 'பழங்கள்',
      'Grains': 'தானியங்கள்',
      'grains': 'தானியங்கள்',
      'Spices': 'மசாலாக்கள்',
      'spices': 'மசாலாக்கள்',
      'Oil Seeds': 'எண்ணெய் வித்துக்கள்',
      'oil_seeds': 'எண்ணெய் வித்துக்கள்',

      // Orders Screen
      'my_orders': 'என் ஆர்டர்கள்',
      'My Orders': 'என் ஆர்டர்கள்',
      'track_manage_orders': 'உங்கள் ஆர்டர்களை கண்காணித்து நிர்வகிக்கவும்',
      'all_orders': 'அனைத்து ஆர்டர்கள்',
      'All Orders': 'அனைத்து ஆர்டர்கள்',
      'Ongoing': 'நடப்பு ஆர்டர்கள்',
      'ongoing': 'நடப்பு ஆர்டர்கள்',
      'Delivered': 'விநியோகிக்கப்பட்டது',
      'delivered': 'விநியோகிக்கப்பட்டது',
      'Cancelled': 'ரத்து செய்யப்பட்டது',
      'cancelled': 'ரத்து செய்யப்பட்டது',
      'Placed': 'ஆர்டர் செய்யப்பட்டது',
      'placed': 'ஆர்டர் செய்யப்பட்டது',
      'Confirmed': 'உறுதி செய்யப்பட்டது',
      'confirmed': 'உறுதி செய்யப்பட்டது',
      'Preparing': 'தயாராகிறது',
      'preparing': 'தயாராகிறது',
      'Picked Up': 'எடுக்கப்பட்டது',
      'picked_up': 'எடுக்கப்பட்டது',
      'Out for Delivery': 'விநியோகத்திற்கு புறப்பட்டது',
      'out_for_delivery': 'விநியோகத்திற்கு புறப்பட்டது',
      'total_amount': 'மொத்த தொகை',
      'Total Amount': 'மொத்த தொகை',
      'payment_status': 'பணம் செலுத்திய நிலை',
      'payment_paid': 'பணம் செலுத்தப்பட்டது',
      'payment_pending': 'பணம் நிலுவையில் உள்ளது',
      'view_details': 'விவரங்களை பார்க்க',
      'View Details': 'விவரங்களை பார்க்க',

      // Transport & Vehicle Assignment
      'assign_transport_title': 'வாகனம் நியமிக்கவும் (விருப்பமானது)',
      'assign_transport_subtitle': 'இந்த ஆர்டருக்கு சரிபார்க்கப்பட்ட குளிர்பதன அல்லது சரக்கு வாகனத்தை தேர்வு செய்க',
      'assign_transport_optional': 'வாகனம் நியமிக்கவும் (விருப்பமானது)',
      'change_vehicle_optional': 'வாகனம் மாற்றவும் (விருப்பமானது)',
      'confirm_assign_vehicle': 'வாகனத்தை உறுதி செய்க',
      'transport': 'போக்குவரத்து',
      'driver': 'ஓட்டுநர்',
      'vehicle': 'வாகனம்',
      'driver_rating': 'ஓட்டுநர் மதிப்பீடு',
      'est_delivery_time': 'மதிப்பிடப்பட்ட விநியோக நேரம்',
      'zero_damage_guarantee': '100% பாதுகாப்பான சேதமற்ற விநியோக உத்தரவாதம்',
      'mutual_assign_notice': 'விவசாயி அல்லது வாங்குபவர் இருவரில் எவரேனும் பரஸ்பர தொடர்பு மூலம் இந்த வாகனத்தை தேர்ந்தெடுக்கலாம்.',
      'call_driver': 'ஓட்டுநரை அழைக்க',
      'call_farmer': 'விவசாயியை அழைக்க',
      'call_buyer': 'வாங்குபவரை அழைக்க',
      'todays_weather': 'இன்றைய வானிலை',
      'farmer_details': 'விவசாயி மற்றும் பண்ணை விவரங்கள்',
      'direct_from_origin': 'பண்ணை நேரடி உற்பத்தி சரிபார்க்கப்பட்டது',
      'quality_checked': 'தரம் ஏ சரிபார்க்கப்பட்டது',
      'otp': 'OTP',
      'pickup_otp': 'எடுக்கும் OTP',
      'delivery_otp': 'விநியோக OTP',
      'eat_fresh': 'புதியதை உண்ணுங்கள்,',
      'Eat Fresh,': 'புதியதை உண்ணுங்கள்,',
      'stay_healthy': 'ஆரோக்கியமாக இருங்கள்',
      'Stay Healthy': 'ஆரோக்கியமாக இருங்கள்',
      'hero_subtitle': 'விவசாயிகளிடமிருந்து நேரடியாக\nபுதிய விளைபொருட்கள் 🌱',
      'shop_now': 'இப்போதே வாங்குங்கள்',
      'Shop Now': 'இப்போதே வாங்குங்கள்',
      'free_delivery_banner': '₹499 க்கு மேல் இலவச டெலிவரி',
      'free_delivery_desc': 'விவசாயிகளுக்கு ஆதரவளிப்போம். புதிதாக உண்போம்.',
      'see_all': 'அனைத்தும்',
      'See All': 'அனைத்தும்',
      'menu': 'பட்டியல்',
      'auctions': 'ஏலங்கள்',
      'bid_fresh_products': 'புதிய விளைபொருட்களுக்கு ஏலம் கேளுங்கள்',
      'chat_with_farmers': 'விவசாயிகளுடன் உரையாட',
      'favorites': 'விருப்பமானவை',
      'todays_deals': 'இன்றைய சலுகைகள்',
      'change_location': 'இருப்பிடத்தை மாற்றுக',
      'help_support': 'உதவி & ஆதரவு',
      'settings': 'அமைப்புகள்',
      'logout': 'வெளியேறு',
      'logout_subtitle': 'உங்கள் கணக்கிலிருந்து வெளியேறவும்',
      'logout_dialog_title': 'வெளியேறவா?',
      'logout_dialog_msg': 'கிசான் AI-லிருந்து நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'cancel': 'ரத்து செய்',
      'retry': 'மீண்டும் முயற்சி செய்க',
      'search_orders_hint': 'ஆர்டர் எண் அல்லது வாங்குபவரை தேடுங்கள்...',
      'no_orders_found': 'ஆர்டர்கள் எதுவும் இல்லை',
      'new_buyer_orders_hint': 'புதிய ஆர்டர்கள் இங்கே தோன்றும்.',
      'load_sample_orders': 'மாதிரி ஆர்டர்களை ஏற்றுக',
      'load_sample_success': 'மாதிரி ஆர்டர்கள் வெற்றிகரமாக ஏற்றப்பட்டன! 🌱',
      'available_label': 'இருப்பு: ',
      'verified_driver': 'சரிபார்க்கப்பட்ட ஓட்டுநர்',
      'vehicle_specs': 'வாகன விவரம்',
      'express_delivery': 'விரைவு விநியோகம்',
      'no_products_category': 'இந்த வகையில் பொருட்கள் இல்லை',
      'no_fresh_products': 'புதிய பொருட்கள் எதுவும் இல்லை',
      'farmers_not_listed': 'விவசாயிகள் இன்னும் எந்த பொருட்களையும் சேர்க்கவில்லை.',
      'try_another_category': 'வேறு வகையை தேர்வு செய்து பார்க்கவும்.',
      'view_all_products': 'அனைத்து பொருட்களையும் பார்க்க',
      'unable_to_load': 'பொருட்களை ஏற்றுவதில் தோல்வி',
      'unable_to_load_orders': 'ஆர்டர்களை ஏற்றுவதில் தோல்வி',

      // Dynamic Crops
      'Tomato': 'தக்காளி',
      'Potato': 'உருளைக்கிழங்கு',
      'Onion': 'வெங்காயம்',
      'Rice': 'அரிசி',
      'Paddy': 'நெல்',
      'Wheat': 'கோதுமை',
      'Carrot': 'கேரட்',
      'Banana': 'வாழைப்பழம்',
      'Mango': 'மாம்பழம்',
      'Chilli': 'பச்சை மிளகாய்',
      'Green Chilli': 'பச்சை மிளகாய்',
      'Brinjal': 'கத்தரிக்காய்',
      'Eggplant': 'கத்தரிக்காய்',
      'Cabbage': 'முட்டைக்கோஸ்',
      'Cauliflower': 'காலிஃபிளவர்',
      'Garlic': 'பூண்டு',
      'Ginger': 'இஞ்சி',
      'Spinach': 'கீரை',
      'Corn': 'சோளம்',
      'Maize': 'மக்காச்சோளம்',
      'Coconut': 'தேங்காய்',
      'Apple': 'ஆப்பிள்',
      'Turmeric': 'மஞ்சள்',
      'Cotton': 'பருத்தி',
      'Sugarcane': 'கரும்பு',
      'Lady\'s Finger': 'வெண்டைக்காய்',
      'Okra': 'வெண்டைக்காய்',
      'Capsicum': 'குடைமிளகாய்',
      'Cucumber': 'வெள்ளரிக்காய்',
      'Beetroot': 'பீட்ரூட்',
      'Coriander': 'கொத்தமல்லி',
      'Mint': 'புதினா',
      'Drumstick': 'முருங்கைக்காய்',
      'Groundnut': 'வேர்க்கடலை',
      'Peanut': 'வேர்க்கடலை',
      'Cardamom': 'ஏலக்காய்',
      'Pepper': 'மிளகு',
      'Black Pepper': 'கருப்பு மிளகு',

      // Order Statuses
      'Pending': 'நிலுவையில் உள்ளது',
      'pending': 'நிலுவையில் உள்ளது',
      'Processing': 'செயலாக்கப்படுகிறது',
      'processing': 'செயலாக்கப்படுகிறது',
      'In Transit': 'பயணத்தில் உள்ளது',
      'in_transit': 'பயணத்தில் உள்ளது',
      'Shipped': 'அனுப்பப்பட்டது',
      'shipped': 'அனுப்பப்பட்டது',
      'Refunded': 'திரும்பி செலுத்தப்பட்டது',
      'refunded': 'திரும்பி செலுத்தப்பட்டது',
      'New': 'புதியது',

      // Weather Conditions & Details
      'Sunny': 'வெயில்',
      'sunny': 'வெயில்',
      'Rainy': 'மழை',
      'rainy': 'மழை',
      'Clear': 'தெளிவான வானிலை',
      'clear': 'தெளிவான வானிலை',
      'Cloudy': 'மேகமூட்டம்',
      'cloudy': 'மேகமூட்டம்',
      'Partly Cloudy': 'பகுதி மேகமூட்டம்',
      'partly_cloudy': 'பகுதி மேகமூட்டம்',
      'Overcast': 'அடர்ந்த மேகமூட்டம்',
      'overcast': 'அடர்ந்த மேகமூட்டம்',
      'Mist': 'பனிமூட்டம்',
      'mist': 'பனிமூட்டம்',
      'Fog': 'மூடுபனி',
      'fog': 'மூடுபனி',
      'Thunderstorm': 'இடியுடன் கூடிய மழை',
      'thunderstorm': 'இடியுடன் கூடிய மழை',
      'Drizzle': 'தூறல்',
      'drizzle': 'தூறல்',
      'Weather Forecast': 'வானிலை முன்னறிவிப்பு',
      'weather_forecast': 'வானிலை முன்னறிவிப்பு',
      'Feels Like': 'உணரப்படும் வெப்பம்',
      'feels_like': 'உணரப்படும் வெப்பம்',
      'Humidity': 'ஈரப்பதம்',
      'humidity': 'ஈரப்பதம்',
      'Wind': 'காற்று',
      'wind': 'காற்று',
      'Precipitation': 'மழைப்பொழிவு',
      'precipitation': 'மழைப்பொழிவு',

      // Filters, Sorting & Cart
      'filter': 'வடிகட்டி',
      'Filter': 'வடிகட்டி',
      'filter_orders': 'ஆர்டர்களை வடிகட்டுக',
      'filter_and_sort': 'வடிகட்டு & வரிசைப்படுத்து',
      'Filter & Sort': 'வடிகட்டு & வரிசைப்படுத்து',
      'sort_by': 'வரிசைப்படுத்து',
      'Sort By': 'வரிசைப்படுத்து',
      'price_low_high': 'விலை: குறைவிலிருந்து அதிகம்',
      'Price: Low to High': 'விலை: குறைவிலிருந்து அதிகம்',
      'price_high_low': 'விலை: அதிகத்திலிருந்து குறைவு',
      'Price: High to Low': 'விலை: அதிகத்திலிருந்து குறைவு',
      'lowest_price': 'குறைந்த விலை',
      'Lowest Price': 'குறைந்த விலை',
      'highest_price': 'அதிக விலை',
      'Highest Price': 'அதிக விலை',
      'quantity_high_low': 'அளவு: அதிகத்திலிருந்து குறைவு',
      'Quantity: High to Low': 'அளவு: அதிகத்திலிருந்து குறைவு',
      'newest': 'சமீபத்தியது',
      'Newest': 'சமீபத்தியது',
      'rating': 'மதிப்பீடு',
      'Rating': 'மதிப்பீடு',
      'all_statuses': 'அனைத்து நிலைகளும்',
      'All Statuses': 'அனைத்து நிலைகளும்',
      'transport_assigned': 'வாகனம் ஒதுக்கப்பட்டது',
      'Transport Assigned': 'வாகனம் ஒதுக்கப்பட்டது',
      'transport_unassigned': 'வாகனம் ஒதுக்கப்படவில்லை',
      'Transport Not Assigned': 'வாகனம் ஒதுக்கப்படவில்லை',
      'reset': 'மீட்டமை',
      'Reset': 'மீட்டமை',
      'apply': 'பயன்படுத்து',
      'Apply': 'பயன்படுத்து',
      'apply_filters': 'வடிகட்டிகளை பயன்படுத்துக',
      'Apply Filters': 'வடிகட்டிகளை பயன்படுத்துக',
      'items': 'பொருட்கள்',
      'Items': 'பொருட்கள்',
      'total': 'மொத்தம்',
      'Total': 'மொத்தம்',
      'checkout': 'செக்அவுட் செய்க',
      'Checkout': 'செக்அவுட் செய்க',
      'empty_cart': 'உங்கள் கூடை காலியாக உள்ளது',
      'empty_cart_desc': 'விவசாய விளைபொருட்களை பார்த்து கூடையில் சேர்க்கவும்.',

      // Farmer Hub (SellScreen)
      'farmer_hub': 'எனது விவசாய மையம்',
      'My Farmer Hub': 'எனது விவசாய மையம்',
      'my_products': 'எனது விளைபொருட்கள்',
      'My Products': 'எனது விளைபொருட்கள்',
      'refresh_listings': 'பட்டியலை புதுப்பிக்கவும்',
      'Refresh Listings': 'பட்டியலை புதுப்பிக்கவும்',
      'farmer_home': 'விவசாயி முகப்பு',
      'Farmer Home': 'விவசாயி முகப்பு',
      'list_your_produce': 'விளைபொருளை பட்டியலிடுங்கள்',
      'List Your Produce': 'விளைபொருளை பட்டியலிடுங்கள்',
      'reach_buyers_ai': 'AI விலை உதவியாளர் மூலம் நேரடியாக வாங்குபவர்களை அணுகவும்.',
      'add_new': 'புதிதாக சேர்',
      'Add New': 'புதிதாக சேர்',
      'my_listings': 'எனது பட்டியல்கள்',
      'My Listings': 'எனது பட்டியல்கள்',
      'active': 'செயலில் உள்ளவை',
      'Active': 'செயலில் உள்ளவை',
      'sold': 'விற்றுத் தீர்ந்தவை',
      'Sold': 'விற்றுத் தீர்ந்தவை',
      'sold_out': 'விற்றுத் தீர்ந்தவை',
      'Sold Out': 'விற்றுத் தீர்ந்தவை',
      'no_products_yet': 'இன்னும் தயாரிப்புகள் எதுவும் பட்டியலிடப்படவில்லை',
      'tap_add_new_intro': "உங்கள் விளைபொருளை பட்டியலிட மேலே உள்ள 'புதிதாக சேர்' என்பதைத் தட்டவும்.",
      'load_starter_products': 'துவக்க தயாரிப்புகளை ஏற்றவும்',
      'products_found': 'பொருட்கள் உள்ளன',
      'no': 'இல்லை',

      // Auction Screen
      'manage_product_auctions': 'உங்கள் விளைபொருள் ஏலங்களை நிர்வகிக்கவும்',
      'my_auctions': 'எனது ஏலங்கள்',
      'My Auctions': 'எனது ஏலங்கள்',
      'upcoming': 'வரவிருக்கும் ஏலங்கள்',
      'Upcoming': 'வரவிருக்கும் ஏலங்கள்',
      'search_auctions_hint': 'ஏலங்களைத் தேடுங்கள்...',
      'start_price': 'தொடக்க விலை',
      'Start Price': 'தொடக்க விலை',
      'current_highest_bid': 'தற்போதைய அதிகபட்ச ஏலம்',
      'Current Highest Bid': 'தற்போதைய அதிகபட்ச ஏலம்',
      'bids': 'ஏலங்கள்',
      'Bids': 'ஏலங்கள்',
      'live': 'நேரலை',
      'LIVE': 'நேரலை',
      'ends_in': 'முடிய இன்னும்',
      'Ends in': 'முடிய இன்னும்',
      'starts_in': 'தொடங்க இன்னும்',
      'Starts in': 'தொடங்க இன்னும்',
      'final_price': 'இறுதி விலை',
      'Final Price': 'இறுதி விலை',
      'winner': 'வெற்றியாளர்',
      'Winner': 'வெற்றியாளர்',
      'create_new_auction': 'புதிய ஏலத்தை உருவாக்கவும்',
      'Create New Auction': 'புதிய ஏலத்தை உருவாக்கவும்',
      'filter_auctions': 'ஏலங்களை வடிகட்டவும்',
      'no_auctions_found': 'ஏலங்கள் எதுவும் கிடைக்கவில்லை',
      'place_bid': 'ஏலம் கேட்கவும்',
      'enter_bid_amount': 'ஏலத்தொகையை உள்ளிடவும்',
      'minimum_bid': 'குறைந்தபட்ச ஏலத்தொகை',
      'auction_details': 'ஏல விவரங்கள்',

      // Weather & Insights
      'view': 'பார்க்க',
      'View': 'பார்க்க',
      '7_day_forecast': '7 நாள் வானிலை முன்னறிவிப்பு',
      'farming_insights': 'விவசாய நுண்ணறிவு',
      'best_irrigation_time': 'சிறந்த நீர்ப்பாசன நேரம்: காலை 6 மணி - 8 மணி',
      'no_heavy_rain': 'இன்று கனமழை எதிர்பார்க்கப்படவில்லை.',
      'suitable_harvest': 'அறுவடைக்கு உகந்த நாள்.',
      'Today': 'இன்று',
      'Tomorrow': 'நாளை',
      'Sunday': 'ஞாயிறு',
      'Monday': 'திங்கள்',
      'Tuesday': 'செவ்வாய்',
      'Wednesday': 'புதன்',
      'Thursday': 'வியாழன்',
      'Friday': 'வெள்ளி',
      'Saturday': 'சனி',
      'uv_index': 'புற ஊதா குறியீடு',
      'High': 'அதிகம்',
      'high': 'அதிகம்',

      // Delivery Partner
      'kisanai_delivery': 'கிசான்AI டெலிவரி',
      'connecting_farms_families': 'பண்ணைகளை குடும்பங்களுடன் இணைக்கிறது',
      'deliver_fresh_produce_today': 'இன்று புதிய விளைபொருட்களை டெலிவரி செய்வோம்!',
      'todays_deliveries': 'இன்றைய டெலிவரிகள்',
      'total_completed': 'மொத்தம் முடிந்தது',
      'offline': 'ஆஃப்லைன்',
      'online': 'ஆன்லைன்',
      'accepting_orders': 'ஆர்டர்களை ஏற்கிறது',
      'map': 'வரைபடம்',
      'profile': 'சுயவிவரம்',
      'no_new_orders_pickup': 'தற்போது புதிய டெலிவரி ஆர்டர்கள் எதுவும் இல்லை',
      'ready_for_pickup_realtime': 'எடுத்துச்செல்ல தயாராக உள்ள ஆர்டர்கள் இங்கே உடனுக்குடன் தோன்றும்.',
      'accept_delivery': 'டெலிவரியை ஏற்கவும்',
      'continue_job': 'பணியைத் தொடரவும்',
      'start_navigation': 'வழிகாட்டலைத் தொடங்கு',
      'start_pickup': 'எடுப்பதை தொடங்கு',
      'pickup_location': 'பொருளெடுக்கும் இடம்',
      'live_delivery_map': 'நேரலை விநியோக வரைபடம்',
      'delivery_fee': 'விநியோகக் கட்டணம்',
      'pickup_address': 'எடுக்கும் முகவரி',
      'drop_address': 'சேர்க்கும் முகவரி',
      'no_active_orders': 'செயலில் உள்ள டெலிவரிகள் எதுவும் இல்லை',
      'no_completed_orders': 'இதுவரை முடிவடைந்த டெலிவரிகள் இல்லை',
      'navigate_to_farm': 'பண்ணைக்கு செல்லவும்',
      'fastest_route': 'வேகமான பாதை',
      'moderate_traffic': 'மிதமான போக்குவரத்து',
      'clear_traffic': 'போக்குவரத்து சீராக உள்ளது',
      'heavy_traffic': 'அதிக போக்குவரத்து',
      'alternate_route': 'மாற்றுப் பாதை',

      // Entrance & Taglines
      'smart_agriculture_tagline': 'ஸ்மார்ட் விவசாயம் & நேரடி சந்தை 🌾',
      'Smart Agriculture & Direct Market 🌾': 'ஸ்மார்ட் விவசாயம் & நேரடி சந்தை 🌾',
      'get_started': 'தொடங்குங்கள்',
      'Get Started': 'தொடங்குங்கள்',
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா? ',
      'Already have an account? ': 'ஏற்கனவே கணக்கு உள்ளதா? ',
      'farmer_role_desc': 'விளைபொருட்களை விற்கவும்,\nவாங்குபவர்களுடன் இணையவும்.',
      'buyer_role_desc': 'விவசாயிகளிடமிருந்து நேரடியாக\nபுதிய விளைபொருட்களை வாங்கவும்.',
      'delivery_role_desc': 'புதிய பண்ணை பொருட்களை விநியோகித்து ஒவ்வொரு பயணத்திலும் சம்பாதிக்கவும்.',
      'Deliver fresh farm produce & earn on every trip.': 'புதிய பண்ணை பொருட்களை விநியோகித்து ஒவ்வொரு பயணத்திலும் சம்பாதிக்கவும்.',
      'trusted': 'நம்பகமானது',
      'Trusted': 'நம்பகமானது',
      'safe_and_secure': 'பாதுகாப்பானது',
      'Safe & secure': 'பாதுகாப்பானது',
      'fresh': 'புதியது',
      'Fresh': 'புதியது',
      'farm_quality': 'பண்ணை தரம்',
      'Farm quality': 'பண்ணை தரம்',
      'fast': 'விரைவானது',
      'Fast': 'விரைவானது',
      'quick_delivery': 'விரைவான விநியோகம்',
      'Quick delivery': 'விரைவான விநியோகம்',
      'together_grow_better': 'ஒன்றிணைந்து சிறந்த நாளையை உருவாக்குவோம் 💚',
      'Together, let’s grow a better tomorrow 💚': 'ஒன்றிணைந்து சிறந்த நாளையை உருவாக்குவோம் 💚',
      'Together, let\'s grow a better tomorrow 💚': 'ஒன்றிணைந்து சிறந்த நாளையை உருவாக்குவோம் 💚',
      'support_farmers_eat_fresh': 'விவசாயிகளை ஆதரிப்போம். புதியதை உண்போம். நலமுடன் வாழ்வோம்.',
      'Support farmers. Eat fresh. Live healthy.': 'விவசாயிகளை ஆதரிப்போம். புதியதை உண்போம். நலமுடன் வாழ்வோம்.',

      // Produce Varieties
      'Sweet Golden Corn': 'இனிப்பு சோளம்',
      'Fresh Farm Bananas (Nendran)': 'புதிய பண்ணை நேந்திரன் வாழைப்பழம்',
      'Sona Masoori Paddy (Grade A)': 'சோனா மசூரி நெல் (தரம் A)',
      'Organic Tomato (Fresh Harvest)': 'இயற்கை தக்காளி (புதிய அறுவடை)',
      'Banganapalli Mango (Grade A)': 'பங்கனப்பள்ளி மாம்பழம் (தரம் A)',

      'Change Vehicle': 'வாகனம் மாற்றவும்',
    },
    'hi': {
      // General & App Branding
      'app_title': 'किसान AI',
      'app_subtitle': 'डायरेक्ट फार्म AI',
      'welcome': 'स्वागत है!',
      'welcome_subtitle': 'चुनें कि आप किसान AI का उपयोग कैसे करना चाहते हैं',
      'good_morning': 'शुभ प्रभात',
      'good_afternoon': 'शुभ दोपहर',
      'good_evening': 'शुभ संध्या',
      'manage_farm_intro': 'अपने खेत, उत्पादों और ऑर्डरों को एक ही स्थान पर प्रबंधित करें।',
      'wallet_balance': 'वॉलेट बैलेंस',
      'view_transactions': 'लेनदेन देखें ›',
      'view_analytics': 'एनालिटिक्स देखें ↗',
      'today_overview': 'आज का विवरण',
      'recent_orders': 'हाल के ऑर्डर',
      'view_all': 'सभी देखें',
      'switch_language': 'भाषा बदलें',
      'choose_language': 'अपनी भाषा चुनें',
      'select_preferred_language': 'अपनी पसंदीदा भाषा चुनें',
      'continue_button': 'जारी रखें',
      'continue_to_login': 'लॉगिन करने के लिए जारी रखें',
      'call': 'कॉल करें',
      'track': 'ट्रैक करें',
      'notes': 'टिप्पणियाँ',

      // Roles
      'farmer': 'किसान',
      'buyer': 'खरीदार',
      'delivery_partner': 'डिलीवरी पार्टनर',

      // Navigation Bar (Farmer & Buyer)
      'Home': 'होम',
      'Products': 'उत्पाद',
      'Produce': 'फसलें',
      'Orders': 'ऑर्डर',
      'Auction': 'नीलामी',
      'Messages': 'संदेश',
      'Market': 'बाजार',
      'Wishlist': 'इच्छासूची',
      'Profile': 'प्रोफ़ाइल',
      'nav_home': 'होम',
      'nav_products': 'उत्पाद',
      'nav_produce': 'फसलें',
      'nav_orders': 'ऑर्डर',
      'nav_auction': 'नीलामी',
      'nav_messages': 'संदेश',
      'nav_market': 'बाजार',
      'nav_wishlist': 'इच्छासूची',
      'nav_profile': 'प्रोफ़ाइल',

      // Quick Actions
      'Quick Actions': 'त्वरित क्रियाएं',
      'quick_actions': 'त्वरित क्रियाएं',
      'voice_assistant': 'आवाज सहायक',
      'quality_scanner': 'AI गुणवत्ता जांच',
      'kisan_pool': 'किसानपूल लॉजिस्टिक्स',
      'offline_sync': 'ऑफ़लाइन सिंक',
      'track_vehicle': 'वाहन ट्रैक करें',
      'add_product': 'फसल जोड़ें',
      'manage_products': 'उत्पाद प्रबंधित करें',
      'analytics': 'विश्लेषण',
      'payouts': 'भुगतान',
      'talk_with_buyers': 'खरीदारों के साथ बातचीत करें',

      // Overview Stats
      'new_orders': 'नए ऑर्डर',
      'New Orders': 'नए ऑर्डर',
      'in_progress': 'प्रगति पर',
      'In Progress': 'प्रगति पर',
      'completed': 'पूर्ण',
      'Completed': 'पूर्ण',
      'today_earnings': 'आज की कमाई',
      "Today's Earnings": 'आज की कमाई',
      'no_new_orders': 'कोई नया ऑर्डर नहीं',
      'no_orders': 'कोई ऑर्डर नहीं',
      'from_completed': 'पूर्ण ऑर्डरों से',

      // Buyer Home
      'fresh_from_farms': 'खेतों से ताज़ा',
      'Fresh from Farms': 'खेतों से ताज़ा',
      'search_placeholder': 'ताज़ी सब्जियां, फल खोजें...',
      'Shop by Category': 'श्रेणी अनुसार खरीदें',
      'shop_by_category': 'श्रेणी अनुसार खरीदें',
      'Fresh Picks for You': 'आपके लिए ताज़ा उत्पाद',
      'fresh_picks': 'आपके लिए ताज़ा उत्पाद',
      'Direct Farm Delivery': 'सीधे खेत से डिलीवरी',
      'direct_farm_delivery': 'सीधे खेत से डिलीवरी',
      'direct_delivery_desc': 'स्थानीय खेतों से सीधे आपके दरवाजे तक तेज़ और सुरक्षित परिवहन।',
      'add_to_cart': 'कार्ट में जोड़ें',
      'Add to Cart': 'कार्ट में जोड़ें',
      'buy_now': 'अभी खरीदें',
      'Buy Now': 'अभी खरीदें',
      'All': 'सभी',
      'all': 'सभी',
      'Vegetables': 'सब्जियां',
      'vegetables': 'सब्जियां',
      'Fruits': 'फल',
      'fruits': 'फल',
      'Grains': 'अनाज',
      'grains': 'अनाज',
      'Spices': 'मसाले',
      'spices': 'मसाले',
      'Oil Seeds': 'तिलहन',
      'oil_seeds': 'तिलहन',

      // Orders Screen
      'my_orders': 'मेरे ऑर्डर',
      'My Orders': 'मेरे ऑर्डर',
      'track_manage_orders': 'अपने ऑर्डर ट्रैक और प्रबंधित करें',
      'all_orders': 'सभी ऑर्डर',
      'All Orders': 'सभी ऑर्डर',
      'Ongoing': 'सक्रिय ऑर्डर',
      'ongoing': 'सक्रिय ऑर्डर',
      'Delivered': 'डिलीवर किया गया',
      'delivered': 'डिलीवर किया गया',
      'Cancelled': 'रद्द किया गया',
      'cancelled': 'रद्द किया गया',
      'Placed': 'ऑर्डर दिया गया',
      'placed': 'ऑर्डर दिया गया',
      'Confirmed': 'पुष्टि की गई',
      'confirmed': 'पुष्टि की गई',
      'Preparing': 'तैयार किया जा रहा है',
      'preparing': 'तैयार किया जा रहा है',
      'Picked Up': 'पिकअप किया गया',
      'picked_up': 'पिकअप किया गया',
      'Out for Delivery': 'डिलीवरी के लिए निकला',
      'out_for_delivery': 'डिलीवरी के लिए निकला',
      'total_amount': 'कुल राशि',
      'Total Amount': 'कुल राशि',
      'payment_status': 'भुगतान स्थिति',
      'payment_paid': 'भुगतान सफल',
      'payment_pending': 'भुगतान लंबित',
      'view_details': 'विवरण देखें',
      'View Details': 'विवरण देखें',

      // Transport & Vehicle Assignment
      'assign_transport_title': 'वाहन असाइन करें (वैकल्पिक)',
      'assign_transport_subtitle': 'इस ऑर्डर के लिए सत्यापित वाहन या कोल्ड-चेन चुनें',
      'assign_transport_optional': 'वाहन असाइन करें (वैकल्पिक)',
      'change_vehicle_optional': 'वाहन बदलें (वैकल्पिक)',
      'confirm_assign_vehicle': 'वाहन पुष्टि करें',
      'transport': 'परिवहन',
      'driver': 'चालक',
      'vehicle': 'वाहन',
      'driver_rating': 'चालक रेटिंग',
      'est_delivery_time': 'अनुमानित डिलीवरी समय',
      'zero_damage_guarantee': '100% सुरक्षित और शून्य क्षति डिलीवरी गारंटी',
      'mutual_assign_notice': 'किसान या खरीदार आपसी बातचीत से इस वाहन को चुन या बदल सकते हैं।',
      'call_driver': 'ड्राइवर को कॉल करें',
      'call_farmer': 'किसान को कॉल करें',
      'call_buyer': 'खरीदार को कॉल करें',
      'todays_weather': 'आज का मौसम',
      'farmer_details': 'किसान और खेत का विवरण',
      'direct_from_origin': 'सीधे खेत से प्रमाणित उपज',
      'quality_checked': 'ग्रेड-ए गुणवत्ता प्रमाणित',
      'otp': 'ओटीपी',
      'pickup_otp': 'पिकअप ओटीपी',
      'delivery_otp': 'डिलीवरी ओटीपी',
      'eat_fresh': 'ताज़ा खाएं,',
      'Eat Fresh,': 'ताज़ा खाएं,',
      'stay_healthy': 'स्वस्थ रहें',
      'Stay Healthy': 'स्वस्थ रहें',
      'hero_subtitle': 'किसानों से सीधे\nताज़ा और शुद्ध उपज 🌱',
      'shop_now': 'अभी खरीदें',
      'Shop Now': 'अभी खरीदें',
      'free_delivery_banner': '₹499 से अधिक पर मुफ्त डिलीवरी',
      'free_delivery_desc': 'किसानों का समर्थन करें। ताज़ा खाएं।',
      'see_all': 'सभी देखें',
      'See All': 'सभी देखें',
      'menu': 'मेनू',
      'auctions': 'नीलामी',
      'bid_fresh_products': 'ताज़ा उत्पादों पर बोली लगाएं',
      'chat_with_farmers': 'किसानों से चैट करें',
      'favorites': 'पसंदीदा',
      'todays_deals': 'आज के सौदे',
      'change_location': 'स्थान बदलें',
      'help_support': 'सहायता और समर्थन',
      'settings': 'सेटिंग्स',
      'logout': 'लॉगआउट',
      'logout_subtitle': 'अपने खाते से साइन आउट करें',
      'logout_dialog_title': 'लॉगआउट करें?',
      'logout_dialog_msg': 'क्या आप निश्चित रूप से किसान AI से लॉगआउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'retry': 'पुनः प्रयास करें',
      'search_orders_hint': 'ऑर्डर आईडी या खरीदार खोजें...',
      'no_orders_found': 'कोई ऑर्डर नहीं मिला',
      'new_buyer_orders_hint': 'नए खरीदार के ऑर्डर यहाँ दिखाई देंगे।',
      'load_sample_orders': 'नमूना ऑर्डर लोड करें',
      'load_sample_success': 'नमूना ऑर्डर सफलतापूर्वक लोड किए गए! 🌱',
      'available_label': 'उपलब्ध: ',
      'verified_driver': 'सत्यापित ड्राइवर',
      'vehicle_specs': 'वाहन विनिर्देश',
      'express_delivery': 'एक्सप्रेस डिलीवरी',
      'no_products_category': 'इस श्रेणी में कोई उत्पाद नहीं है',
      'no_fresh_products': 'कोई ताज़ा उत्पाद उपलब्ध नहीं है',
      'farmers_not_listed': 'किसानों ने अभी तक कोई उत्पाद सूचीबद्ध नहीं किया है।',
      'try_another_category': 'कृपया दूसरी श्रेणी का चयन करें।',
      'view_all_products': 'सभी उत्पाद देखें',
      'unable_to_load': 'उत्पाद लोड करने में असमर्थ',
      'unable_to_load_orders': 'ऑर्डर लोड करने में असमर्थ',

      // Dynamic Crops
      'Tomato': 'टमाटर',
      'Potato': 'आलू',
      'Onion': 'प्याज',
      'Rice': 'चावल',
      'Paddy': 'धान',
      'Wheat': 'गेहूं',
      'Carrot': 'गाजर',
      'Banana': 'केला',
      'Mango': 'आम',
      'Chilli': 'हरी मिर्च',
      'Green Chilli': 'हरी मिर्च',
      'Brinjal': 'बैंगन',
      'Eggplant': 'बैंगन',
      'Cabbage': 'पत्तागोभी',
      'Cauliflower': 'फूलगोभी',
      'Garlic': 'लहसुन',
      'Ginger': 'अदरक',
      'Spinach': 'पालक',
      'Corn': 'मक्का',
      'Maize': 'मक्का',
      'Coconut': 'नारियल',
      'Apple': 'सेब',
      'Turmeric': 'हल्दी',
      'Cotton': 'कपास',
      'Sugarcane': 'गन्ना',
      'Lady\'s Finger': 'भिंडी',
      'Okra': 'भिंडी',
      'Capsicum': 'शिमला मिर्च',
      'Cucumber': 'खीरा',
      'Beetroot': 'चुकंदर',
      'Coriander': 'धनिया',
      'Mint': 'पुदीना',
      'Drumstick': 'सहजन',
      'Groundnut': 'मूंगफली',
      'Peanut': 'मूंगफली',
      'Cardamom': 'इलायची',
      'Pepper': 'काली मिर्च',
      'Black Pepper': 'काली मिर्च',

      // Order Statuses
      'Pending': 'लंबित',
      'pending': 'लंबित',
      'Processing': 'प्रक्रियाधीन',
      'processing': 'प्रक्रियाधीन',
      'In Transit': 'रास्ते में है',
      'in_transit': 'रास्ते में है',
      'Shipped': 'भेज दिया गया',
      'shipped': 'भेज दिया गया',
      'Refunded': 'धनवापसी हुई',
      'refunded': 'धनवापसी हुई',
      'New': 'नया',

      // Weather Conditions & Details
      'Sunny': 'धूप',
      'sunny': 'धूप',
      'Rainy': 'बारिश',
      'rainy': 'बारिश',
      'Clear': 'साफ मौसम',
      'clear': 'साफ मौसम',
      'Cloudy': 'बादल',
      'cloudy': 'बादल',
      'Partly Cloudy': 'आंशिक रूप से बादल',
      'partly_cloudy': 'आंशिक रूप से बादल',
      'Overcast': 'घटाटोप',
      'overcast': 'घटाटोप',
      'Mist': 'धुंध',
      'mist': 'धुंध',
      'Fog': 'कोहरा',
      'fog': 'कोहरा',
      'Thunderstorm': 'गरज के साथ बारिश',
      'thunderstorm': 'गरज के साथ बारिश',
      'Drizzle': 'बूंदाबांदी',
      'drizzle': 'बूंदाबांदी',
      'Weather Forecast': 'मौसम का पूर्वानुमान',
      'weather_forecast': 'मौसम का पूर्वानुमान',
      'Feels Like': 'अनुभव तापमान',
      'feels_like': 'अनुभव तापमान',
      'Humidity': 'आर्द्रता',
      'humidity': 'आर्द्रता',
      'Wind': 'हवा',
      'wind': 'हवा',
      'Precipitation': 'वर्षण',
      'precipitation': 'वर्षण',

      // Filters, Sorting & Cart
      'filter': 'फ़िल्टर',
      'Filter': 'फ़िल्टर',
      'filter_orders': 'ऑर्डर फ़िल्टर करें',
      'filter_and_sort': 'फ़िल्टर और क्रमबद्ध करें',
      'Filter & Sort': 'फ़िल्टर और क्रमबद्ध करें',
      'sort_by': 'क्रमबद्ध करें',
      'Sort By': 'क्रमबद्ध करें',
      'price_low_high': 'कीमत: कम से ज्यादा',
      'Price: Low to High': 'कीमत: कम से ज्यादा',
      'price_high_low': 'कीमत: ज्यादा से कम',
      'Price: High to Low': 'कीमत: ज्यादा से कम',
      'lowest_price': 'सबसे कम कीमत',
      'Lowest Price': 'सबसे कम कीमत',
      'highest_price': 'सबसे अधिक कीमत',
      'Highest Price': 'सबसे अधिक कीमत',
      'quantity_high_low': 'मात्रा: अधिक से कम',
      'Quantity: High to Low': 'मात्रा: अधिक से कम',
      'newest': 'नवीनतम',
      'Newest': 'नवीनतम',
      'rating': 'रेटिंग',
      'Rating': 'रेटिंग',
      'all_statuses': 'सभी स्थितियाँ',
      'All Statuses': 'सभी स्थितियाँ',
      'transport_assigned': 'वाहन सौंपा गया',
      'Transport Assigned': 'वाहन सौंपा गया',
      'transport_unassigned': 'वाहन नहीं सौंपा गया',
      'Transport Not Assigned': 'वाहन नहीं सौंपा गया',
      'reset': 'रीसेट',
      'Reset': 'रीसेट',
      'apply': 'लागू करें',
      'Apply': 'लागू करें',
      'apply_filters': 'फ़िल्टर लागू करें',
      'Apply Filters': 'फ़िल्टर लागू करें',
      'items': 'वस्तुएं',
      'Items': 'वस्तुएं',
      'total': 'कुल',
      'Total': 'कुल',
      'checkout': 'चेकआउट करें',
      'Checkout': 'चेकआउट करें',
      'empty_cart': 'आपकी कार्ट खाली है',
      'empty_cart_desc': 'खेत के ताज़ा उत्पादों को देखें और अपनी कार्ट में जोड़ें।',

      // Farmer Hub (SellScreen)
      'farmer_hub': 'किसान हब',
      'My Farmer Hub': 'मेरा किसान हब',
      'my_products': 'मेरे उत्पाद',
      'My Products': 'मेरे उत्पाद',
      'refresh_listings': 'सूची ताज़ा करें',
      'Refresh Listings': 'सूची ताज़ा करें',
      'farmer_home': 'किसान होम',
      'Farmer Home': 'किसान होम',
      'list_your_produce': 'अपनी उपज सूचीबद्ध करें',
      'List Your Produce': 'अपनी उपज सूचीबद्ध करें',
      'reach_buyers_ai': 'AI मूल्य सहायक से खरीदारों तक सीधे पहुंचें।',
      'add_new': 'नया जोड़ें',
      'Add New': 'नया जोड़ें',
      'my_listings': 'मेरी सूचियाँ',
      'My Listings': 'मेरी सूचियाँ',
      'active': 'सक्रिय',
      'Active': 'सक्रिय',
      'sold': 'बिक गया',
      'Sold': 'बिक गया',
      'sold_out': 'बिक गया',
      'Sold Out': 'बिक गया',
      'no_products_yet': 'अभी तक कोई उत्पाद सूचीबद्ध नहीं है',
      'tap_add_new_intro': "अपनी उपज जोड़ने के लिए ऊपर 'नया जोड़ें' पर टैप करें।",
      'load_starter_products': 'शुरुआती उत्पाद लोड करें',
      'products_found': 'उत्पाद मिले',
      'no': 'नहीं',

      // Auction Screen
      'manage_product_auctions': 'अपने उत्पाद की नीलामियों को प्रबंधित करें',
      'my_auctions': 'मेरी नीलामी',
      'My Auctions': 'मेरी नीलामी',
      'upcoming': 'आगामी',
      'Upcoming': 'आगामी',
      'search_auctions_hint': 'नीलामी खोजें...',
      'start_price': 'प्रारंभिक मूल्य',
      'Start Price': 'प्रारंभिक मूल्य',
      'current_highest_bid': 'वर्तमान उच्चतम बोली',
      'Current Highest Bid': 'वर्तमान उच्चतम बोली',
      'bids': 'बोलियां',
      'Bids': 'बोलियां',
      'live': 'लाइव',
      'LIVE': 'लाइव',
      'ends_in': 'समाप्त होगा',
      'Ends in': 'समाप्त होगा',
      'starts_in': 'शुरू होगा',
      'Starts in': 'शुरू होगा',
      'final_price': 'अंतिम मूल्य',
      'Final Price': 'अंतिम मूल्य',
      'winner': 'विजेता',
      'Winner': 'विजेता',
      'create_new_auction': 'नई नीलामी बनाएं',
      'Create New Auction': 'नई नीलामी बनाएं',
      'filter_auctions': 'नीलामी फ़िल्टर करें',
      'no_auctions_found': 'कोई नीलामी नहीं मिली',
      'place_bid': 'बोली लगाएं',
      'enter_bid_amount': 'बोली राशि दर्ज करें',
      'minimum_bid': 'न्यूनतम बोली',
      'auction_details': 'नीलामी विवरण',

      // Weather & Insights
      'view': 'देखें',
      'View': 'देखें',
      '7_day_forecast': '7 दिवसीय मौसम पूर्वानुमान',
      'farming_insights': 'कृषि अंतर्दृष्टि',
      'best_irrigation_time': 'सिंचाई का सर्वोत्तम समय: सुबह 6 - 8 बजे',
      'no_heavy_rain': 'आज भारी बारिश की संभावना नहीं है।',
      'suitable_harvest': 'फसल कटाई के लिए उपयुक्त दिन।',
      'Today': 'आज',
      'Tomorrow': 'कल',
      'Sunday': 'रविवार',
      'Monday': 'सोमवार',
      'Tuesday': 'मंगलवार',
      'Wednesday': 'बुधवार',
      'Thursday': 'गुरुवार',
      'Friday': 'शुक्रवार',
      'Saturday': 'शनिवार',
      'uv_index': 'यूवी इंडेक्स',
      'High': 'उच्च',
      'high': 'उच्च',

      // Delivery Partner
      'kisanai_delivery': 'किसान AI डिलीवरी',
      'connecting_farms_families': 'खेतों को परिवारों से जोड़ना',
      'deliver_fresh_produce_today': 'आज ताज़ा उपज पहुंचाएं!',
      'todays_deliveries': 'आज की डिलीवरी',
      'total_completed': 'कुल पूर्ण',
      'offline': 'ऑफ़लाइन',
      'online': 'ऑनलाइन',
      'accepting_orders': 'ऑर्डर स्वीकार कर रहे हैं',
      'map': 'मानचित्र',
      'profile': 'प्रोफ़ाइल',
      'no_new_orders_pickup': 'पिकअप के लिए कोई नया डिलीवरी ऑर्डर नहीं है',
      'ready_for_pickup_realtime': 'पिकअप के लिए तैयार ऑर्डर यहां रीयल-टाइम में दिखाई देंगे।',
      'accept_delivery': 'डिलीवरी स्वीकार करें',
      'continue_job': 'कार्य जारी रखें',
      'start_navigation': 'नेविगेशन शुरू करें',
      'start_pickup': 'पिकअप शुरू करें',
      'pickup_location': 'पिकअप स्थान पर जाएं',
      'live_delivery_map': 'लाइव डिलीवरी मानचित्र',
      'delivery_fee': 'वितरण शुल्क',
      'pickup_address': 'पिकअप पता',
      'drop_address': 'ड्रॉप पता',
      'no_active_orders': 'कोई सक्रिय डिलीवरी नहीं है',
      'no_completed_orders': 'अभी तक कोई पूर्ण डिलीवरी नहीं है',
      'navigate_to_farm': 'खेत पर नेविगेट करें',
      'fastest_route': 'सबसे तेज़ मार्ग',
      'moderate_traffic': 'मध्यम यातायात',
      'clear_traffic': 'स्पष्ट यातायात',
      'heavy_traffic': 'भारी यातायात',
      'alternate_route': 'वैकल्पिक मार्ग',

      // Entrance & Taglines
      'smart_agriculture_tagline': 'स्मार्ट कृषि और सीधा बाज़ार 🌾',
      'Smart Agriculture & Direct Market 🌾': 'स्मार्ट कृषि और सीधा बाज़ार 🌾',
      'get_started': 'शुरू करें',
      'Get Started': 'शुरू करें',
      'already_have_account': 'क्या आपके पास पहले से खाता है? ',
      'Already have an account? ': 'क्या आपके पास पहले से खाता है? ',
      'farmer_role_desc': 'अपनी उपज बेचें,\nखरीदारों से सीधे जुड़ें।',
      'buyer_role_desc': 'किसानों से सीधे\nताज़ा उत्पाद खरीदें।',
      'delivery_role_desc': 'ताज़ा कृषि उत्पाद पहुंचाएं और हर ट्रिप पर कमाई करें।',
      'Deliver fresh farm produce & earn on every trip.': 'ताज़ा कृषि उत्पाद पहुंचाएं और हर ट्रिप पर कमाई करें।',
      'trusted': 'विश्वसनीय',
      'Trusted': 'विश्वसनीय',
      'safe_and_secure': 'सुरक्षित',
      'Safe & secure': 'सुरक्षित',
      'fresh': 'ताज़ा',
      'Fresh': 'ताज़ा',
      'farm_quality': 'खेत की गुणवत्ता',
      'Farm quality': 'खेत की गुणवत्ता',
      'fast': 'तेज़',
      'Fast': 'तेज़',
      'quick_delivery': 'त्वरित डिलीवरी',
      'Quick delivery': 'त्वरित डिलीवरी',
      'together_grow_better': 'आइए मिलकर एक बेहतर कल का निर्माण करें 💚',
      'Together, let’s grow a better tomorrow 💚': 'आइए मिलकर एक बेहतर कल का निर्माण करें 💚',
      'Together, let\'s grow a better tomorrow 💚': 'आइए मिलकर एक बेहतर कल का निर्माण करें 💚',
      'support_farmers_eat_fresh': 'किसानों का समर्थन करें। ताज़ा खाएं। स्वस्थ रहें।',
      'Support farmers. Eat fresh. Live healthy.': 'किसानों का समर्थन करें। ताज़ा खाएं। स्वस्थ रहें।',

      // Produce Varieties
      'Sweet Golden Corn': 'मीठा मक्का (स्वीट कॉर्न)',
      'Fresh Farm Bananas (Nendran)': 'ताज़ा केले (नेन्द्रन)',
      'Sona Masoori Paddy (Grade A)': 'सोना मसूरी धान (ग्रेड ए)',
      'Organic Tomato (Fresh Harvest)': 'जैविक टमाटर (ताज़ा फसल)',
      'Banganapalli Mango (Grade A)': 'बंगनापल्ली आम (ग्रेड ए)',

      'Change Vehicle': 'वाहन बदलें',
    },
  };
}

