// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE5o10OrVfTJff8r1bfGWl54o042sSres',
    appId: '1:704420931000:web:239a29132ef9683d1f1b4d',
    messagingSenderId: '704420931000',
    projectId: 'vidhai-747d5',
    authDomain: 'vidhai-747d5.firebaseapp.com',
    storageBucket: 'vidhai-747d5.firebasestorage.app',
    measurementId: 'G-8B2N6RDD1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpeox-XKrNbpeHN-fd0qMQpewwnOsyrtU',
    appId: '1:704420931000:android:f4af95bfd1ccc9aa1f1b4d',
    messagingSenderId: '704420931000',
    projectId: 'vidhai-747d5',
    storageBucket: 'vidhai-747d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8K6dpxVPlznDp14XSy5Ix7wpGgAVjho',
    appId: '1:704420931000:ios:04e2d05ad25d50bb1f1b4d',
    messagingSenderId: '704420931000',
    projectId: 'vidhai-747d5',
    storageBucket: 'vidhai-747d5.firebasestorage.app',
    iosBundleId: 'com.example.sem7Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm8K6dpxVPlznDp14XSy5Ix7wpGgAVjho',
    appId: '1:704420931000:ios:04e2d05ad25d50bb1f1b4d',
    messagingSenderId: '704420931000',
    projectId: 'vidhai-747d5',
    storageBucket: 'vidhai-747d5.firebasestorage.app',
    iosBundleId: 'com.example.sem7Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE5o10OrVfTJff8r1bfGWl54o042sSres',
    appId: '1:704420931000:web:cbcc8909efc9d7671f1b4d',
    messagingSenderId: '704420931000',
    projectId: 'vidhai-747d5',
    authDomain: 'vidhai-747d5.firebaseapp.com',
    storageBucket: 'vidhai-747d5.firebasestorage.app',
    measurementId: 'G-ZR6JBNT13L',
  );
}
